info:
  component: API Gateway
  
server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-integration
        uri:
          lb://user-integration
        predicates:
        - Path=/api/user/**
        filters:
        - StripPrefix=2