info:
  component: Department Service
  
server:
  port: 8102

eureka:
  client:
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

